from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from scripts.dependency_locks import load_policy
from scripts.verify_dependency_locks import main, verify_dependency_locks


REPO_ROOT = Path(__file__).resolve().parent.parent


def _copy_lock_contract(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    (repo / "requirements").mkdir(parents=True)
    policy = load_policy(REPO_ROOT)
    for relative in policy.inputs + policy.outputs:
        destination = repo / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(REPO_ROOT / relative, destination)
    shutil.copy2(REPO_ROOT / "requirements/lock-policy.toml", repo / "requirements")
    shutil.copy2(REPO_ROOT / "requirements/image-lock.json", repo / "requirements")
    return repo


def _replace_once(path: Path, old: str, new: str) -> None:
    source = path.read_text(encoding="utf-8")
    mutated = source.replace(old, new, 1)
    assert mutated != source
    path.write_text(mutated, encoding="utf-8")


def test_live_generated_lock_family_passes_offline_verification(capsys: object) -> None:
    assert verify_dependency_locks(REPO_ROOT) == ()
    assert main(["--repo-root", str(REPO_ROOT)]) == 0


@pytest.mark.parametrize(
    ("relative", "old", "new", "category"),
    (
        (
            "requirements/locks/bootstrap.txt",
            "# policy-sha256: ",
            "# policy-sha256: 0",
            "header",
        ),
        (
            "requirements/locks/bootstrap.txt",
            "# input-sha256: requirements.txt=",
            "# input-sha256: requirements.txt=0",
            "header",
        ),
        (
            "requirements/locks/bootstrap.txt",
            "--hash=sha256:",
            "--hash=sha256:xyz",
            "content",
        ),
        (
            "requirements/locks/darwin-arm64/core.txt",
            "torch==2.11.0",
            "torch==2.10.0",
            "pin",
        ),
        (
            "requirements/locks/linux-aarch64/runtime.txt",
            "pyg-lib==0.8.0+pt211cpu",
            "pyg-lib==0.8.0+pt210cpu",
            "pin",
        ),
        (
            "requirements/locks/darwin-arm64/root.txt",
            "en_core_web_sm-3.8.0-py3-none-any.whl",
            "en_core_web_sm-3.7.0-py3-none-any.whl",
            "source",
        ),
        (
            "requirements/locks/darwin-arm64/root.txt",
            "# target: darwin-arm64",
            "# target: linux-aarch64",
            "header",
        ),
        (
            "requirements/locks/darwin-arm64/root.txt",
            "# Generated by",
            "# /private/tmp/secret Generated by",
            "content",
        ),
    ),
)
def test_offline_verifier_rejects_authority_and_content_mutations(
    tmp_path: Path, relative: str, old: str, new: str, category: str
) -> None:
    repo = _copy_lock_contract(tmp_path)
    _replace_once(repo / relative, old, new)

    findings = verify_dependency_locks(repo)

    assert category in {finding.category for finding in findings}
    assert all(not finding.path.startswith("/") for finding in findings)


def test_valid_but_wrong_artifact_hash_is_offline_syntactically_coherent(tmp_path: Path) -> None:
    repo = _copy_lock_contract(tmp_path)
    lock = repo / "requirements/locks/bootstrap.txt"
    source = lock.read_text(encoding="utf-8")
    start = source.index("--hash=sha256:") + len("--hash=sha256:")
    mutated = source[:start] + "0" * 64 + source[start + 64 :]
    assert mutated != source
    lock.write_text(mutated, encoding="utf-8")

    assert verify_dependency_locks(repo) == ()


def test_missing_generated_lock_has_stable_inventory_finding(tmp_path: Path) -> None:
    repo = _copy_lock_contract(tmp_path)
    (repo / "requirements/locks/compiler.txt").unlink()

    findings = verify_dependency_locks(repo)

    assert findings
    assert any(
        finding.category == "inventory"
        and finding.path == "requirements/locks/compiler.txt"
        for finding in findings
    )


def test_cli_failure_is_stable_and_redacted(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    repo = _copy_lock_contract(tmp_path)
    lock = repo / "requirements/locks/bootstrap.txt"
    lock.write_text("/private/tmp/secret\n", encoding="utf-8")

    assert main(["--repo-root", str(repo)]) == 1
    captured = capsys.readouterr()
    assert captured.out == ""
    assert "/private" not in captured.err
    assert "dependency lock verification failed:" in captured.err
