"""Offline validation for generated dependency lock artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from packaging.version import Version

from scripts.dependency_locks import (
    DependencyLockError,
    LockedRequirement,
    TargetEnvironment,
    load_policy,
    parse_lock,
    project_for_target,
)


@dataclass(frozen=True)
class LockFinding:
    category: str
    path: str
    detail: str


@dataclass(frozen=True)
class NetworkCheckScope:
    lock_check: bool
    image_check: bool


_GENERATOR_LINE = "# Generated by python -m scripts.lock_dependencies; do not edit."
_MODEL_URL = (
    "https://github.com/explosion/spacy-models/releases/download/"
    "en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl"
)
_MODEL_HASH = "1932429db727d4bff3deed6b34cfc05df17794f4a52eeb26cf8928f7c1a0fb85"
_FULL_SHA = re.compile(r"[0-9a-f]{40}")
_DEPENDENCY_PATHS = frozenset(
    {
        "requirements.txt",
        "bootstrap-requirements.txt",
        "compiler-requirements.txt",
        "docs-requirements.in",
        "docs-requirements.txt",
        "vulnerability-audit-requirements.txt",
        "atlas-contract-requirements.txt",
        "torch-core-requirements.txt",
        "torch-ecosystem-requirements.txt",
        "torch-requirements.txt",
        "torch-audit-requirements.txt",
        "pyg-extension-audit-requirements.txt",
        "requirements/lock-policy.toml",
        "Makefile",
        "scripts/dependency_locks.py",
        "scripts/lock_dependencies.py",
        "scripts/install_locked_requirements.py",
        "scripts/install_torch_stack.py",
        "scripts/verify_dependency_locks.py",
        "scripts/advisory_baseline.py",
        "security/accepted-advisories.json",
    }
)
_IMAGE_PATHS = frozenset(
    {
        "requirements/image-lock.json",
        "scripts/check_image_locks.py",
    }
)
_BOTH_PATHS = frozenset(
    {
        "Dockerfile",
        ".devcontainer/devcontainer.json",
        ".github/workflows/ci.yml",
    }
)
_DOCUMENTATION_CONTRACT: dict[Path, tuple[str, ...]] = {
    Path("README.md"): (
        "requirements/lock-policy.toml",
        "reproducible for the qualified platform lock",
        "exact resolver cutoff",
        "make lock-check",
        "make image-lock-check",
    ),
    Path("CONTRIBUTING.md"): (
        "requirements/lock-policy.toml",
        "exact resolver cutoff",
        "make lock-write",
        "make lock-check",
        "make image-lock-check",
    ),
    Path("SECURITY.md"): (
        "requirements/lock-policy.toml",
        "exact lock-derived",
        "make lock-check",
        "make image-lock-check",
    ),
    Path("CHANGELOG.md"): ("Issue #63", "requirements/lock-policy.toml"),
    Path("docs/env-setup.md"): (
        "requirements/lock-policy.toml",
        "reproducible for that qualified",
        "requirements/image-lock.json",
    ),
    Path("docs/architecture.md"): (
        "requirements/lock-policy.toml",
        "CONDA_AUTO_ACTIVATE_BASE=false",
        "requirements/image-lock.json",
    ),
    Path("docs/dependency-contracts.md"): (
        "Current Issue #63 locked four-surface audit",
        "requirements/lock-policy.toml",
        "exact resolver cutoff",
        "make lock-write",
        "make lock-check",
        "make image-lock-check",
        "Issue #64",
        "Issue #65",
        "Issue #66",
    ),
    Path("docs/notebook-infrastructure.md"): (
        "requirements/lock-policy.toml",
        "qualified platform lock",
    ),
    Path("docs/conventions.md"): (
        "hash-required Linux lock",
        "requirements/locks/atlas-contract.txt",
        "exact lock-derived, no-resolve projections",
    ),
    Path("docs/jupyterhub-integration.md"): (
        "exact Python 3.11.15",
        "requirements/locks/atlas-contract.txt",
    ),
    Path("docs/nnx-library.md"): (
        "make install-torch-stack",
        "selected hash-required platform lock",
    ),
    Path("docs/notebooks/text_classification-agnews-spacy-mlp-pytorch.md"): (
        "en-core-web-sm==3.8.0",
        "requirements/lock-policy.toml",
    ),
    Path("notebooks/text_classification-agnews-spacy-mlp-pytorch/docs/spec.yaml"): (
        "en-core-web-sm==3.8.0",
        "requirements/lock-policy.toml",
    ),
}
_FORBIDDEN_CURRENT_DOCUMENTATION = (
    "python -m spacy download",
    "pip install -r requirements.txt",
    "uv pip compile",
    "docker pull latest",
    "CONDA_AUTO_ACTIVATE_BASE=true",
    "perfectly reproducible across every platform",
    "Issue #63 retains ownership of full dependency locks",
    "remain Issue #63 work",
)


def classify_network_checks(
    event_name: str, changed_paths: Sequence[str] | None
) -> NetworkCheckScope:
    """Select network checks, failing closed when change scope is not trustworthy."""

    if event_name in {"schedule", "workflow_dispatch"}:
        return NetworkCheckScope(True, True)
    if event_name not in {"pull_request", "push"} or not changed_paths:
        return NetworkCheckScope(True, True)
    paths = tuple(changed_paths)
    if any(
        not path
        or Path(path).is_absolute()
        or ".." in Path(path).parts
        or "\\" in path
        for path in paths
    ):
        return NetworkCheckScope(True, True)

    lock_check = False
    image_check = False
    for path in paths:
        if path in _BOTH_PATHS:
            lock_check = True
            image_check = True
        if (
            path in _DEPENDENCY_PATHS
            or path.startswith("requirements/locks/")
            or path.startswith(".github/workflows/")
        ):
            lock_check = True
        if path in _IMAGE_PATHS:
            image_check = True
    return NetworkCheckScope(lock_check, image_check)


def _documentation_findings(repo: Path) -> list[LockFinding]:
    findings: list[LockFinding] = []
    for path, required in _DOCUMENTATION_CONTRACT.items():
        try:
            source = (repo / path).read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            findings.append(_finding("documentation", path, "missing"))
            continue
        current = source.split("## [0.1.0]", 1)[0] if path == Path("CHANGELOG.md") else source
        if any(fragment not in current for fragment in required):
            findings.append(_finding("documentation", path, "required lock contract"))
            continue
        if any(fragment in current for fragment in _FORBIDDEN_CURRENT_DOCUMENTATION):
            findings.append(_finding("documentation", path, "stale install contract"))
    return findings


def _changed_paths(repo: Path, base: str, head: str) -> tuple[str, ...] | None:
    if not _FULL_SHA.fullmatch(base) or not _FULL_SHA.fullmatch(head):
        return None
    try:
        completed = subprocess.run(
            ("git", "diff", "--name-only", "--no-renames", f"{base}...{head}"),
            cwd=repo,
            text=True,
            capture_output=True,
            check=False,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if completed.returncode != 0:
        return None
    return tuple(completed.stdout.splitlines())


def _write_scope(path: Path, scope: NetworkCheckScope) -> None:
    with path.open("a", encoding="utf-8") as stream:
        stream.write(f"lock-check={str(scope.lock_check).lower()}\n")
        stream.write(f"image-check={str(scope.image_check).lower()}\n")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _target_for(platform: object) -> TargetEnvironment:
    values = dict(platform.marker_environment)
    values.update(
        {
            "implementation_version": "3.11.0",
            "python_full_version": "3.11.0",
            "extra": "",
        }
    )
    return TargetEnvironment(key=platform.key, marker_environment=values)


def _expected_header(repo: Path, policy: object, target: str) -> tuple[str, ...]:
    lines = (
        _GENERATOR_LINE,
        f"# policy-sha256: {_sha256(repo / 'requirements/lock-policy.toml')}",
        f"# target: {target}",
    )
    inputs = tuple(
        f"# input-sha256: {relative.as_posix()}={_sha256(repo / relative)}"
        for relative in policy.inputs
    )
    return lines + inputs


def _finding(category: str, relative: Path, detail: str) -> LockFinding:
    return LockFinding(category, relative.as_posix(), detail)


def _requirements_by_name(
    requirements: Sequence[LockedRequirement], target: TargetEnvironment | None = None
) -> dict[str, LockedRequirement]:
    selected = requirements if target is None else project_for_target(requirements, target)
    return {requirement.name: requirement for requirement in selected}


def _target_name(relative: Path) -> str:
    parts = relative.parts
    if len(parts) >= 4 and parts[:2] == ("requirements", "locks"):
        return parts[2]
    return "supported-matrix"


def _consumer_findings(repo: Path) -> list[LockFinding]:
    findings: list[LockFinding] = []
    torch_path = Path("scripts/install_torch_stack.py")
    helper_path = Path("scripts/install_locked_requirements.py")
    make_path = Path("Makefile")
    try:
        torch_source = (repo / torch_path).read_text(encoding="utf-8")
        helper_source = (repo / helper_path).read_text(encoding="utf-8")
        make_source = (repo / make_path).read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return [_finding("consumer", torch_path, "missing")]
    torch_contract = (
        torch_source.count('"--require-hashes",') == 1
        and torch_source.count('"--only-binary=:all:",') == 4
        and torch_source.count('"--no-binary=python-louvain",') == 1
        and torch_source.count('"--no-build-isolation",') == 1
        and "requirements/locks/bootstrap.txt" in torch_source
        and "requirements/locks/{target}" in torch_source
        and torch_source.count(
            '"https://download.pytorch.org/whl/cpu/torchao"'
        )
        == 1
        and "torch-core-requirements.txt" not in torch_source
        and '"requirements.txt"' not in torch_source
    )
    if not torch_contract:
        findings.append(_finding("consumer", torch_path, "four-stage installer"))
    role_paths = {
        '"bootstrap": "requirements/locks/bootstrap.txt"',
        '"compiler": "requirements/locks/compiler.txt"',
        '"docs": "docs-requirements.txt"',
        '"audit": "requirements/locks/audit.txt"',
        '"atlas-contract": "requirements/locks/atlas-contract.txt"',
    }
    if any(helper_source.count(fragment) != 1 for fragment in role_paths):
        findings.append(_finding("consumer", helper_path, "role map"))
    make_contract = {
        "install-bootstrap": "bootstrap",
        "install-compiler-lock": "compiler",
        "install-docs-lock": "docs",
        "install-audit-lock": "audit",
        "install-atlas-contract-lock": "atlas-contract",
    }
    for target, role in make_contract.items():
        block = f"{target}:\n\t$(PYTHON) -m scripts.install_locked_requirements {role}"
        if make_source.count(block) != 1:
            findings.append(_finding("consumer", make_path, target))
    if "spacy download" in make_source:
        findings.append(_finding("consumer", make_path, "package-changing NLP assets"))
    workflow_paths = tuple(
        Path(".github/workflows") / name
        for name in ("ci.yml", "docs.yml", "pages.yml", "atlas-contract.yml")
    )
    try:
        workflow_sources = {
            path: (repo / path).read_text(encoding="utf-8") for path in workflow_paths
        }
        docker_path = Path("Dockerfile")
        devcontainer_path = Path(".devcontainer/devcontainer.json")
        image_path = Path("requirements/image-lock.json")
        docker_source = (repo / docker_path).read_text(encoding="utf-8")
        devcontainer_source = (repo / devcontainer_path).read_text(encoding="utf-8")
        image_payload = json.loads((repo / image_path).read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        findings.append(_finding("consumer", Path(".github/workflows"), "missing"))
        return findings

    required_cache_paths = (
        "requirements/lock-policy.toml",
        "requirements/locks/bootstrap.txt",
        *(relative.as_posix() for relative in load_policy(repo).inputs),
    )
    for path, source in workflow_sources.items():
        if 'python-version: "3.11"' in source or "pip install" in source:
            findings.append(_finding("consumer", path, "mutable Python install"))
        setup_blocks = source.split("actions/setup-python@")[1:]
        for block in setup_blocks:
            block = block.split("\n      - name:", 1)[0]
            role_paths: tuple[str, ...]
            if "requirements/locks/audit.txt" in block:
                role_paths = tuple(relative.as_posix() for relative in load_policy(repo).outputs)
            elif "requirements/locks/linux-x86_64/" in block:
                role_paths = tuple(
                    f"requirements/locks/linux-x86_64/{name}.txt"
                    for name in ("core", "runtime", "root")
                )
            elif "requirements/locks/atlas-contract.txt" in block:
                role_paths = ("requirements/locks/atlas-contract.txt",)
            elif "docs-requirements.txt" in block:
                role_paths = ("docs-requirements.txt",)
            else:
                role_paths = ()
            if (
                'python-version: "3.11.15"' not in block
                or "cache: pip" not in block
                or any(relative not in block for relative in required_cache_paths)
                or not role_paths
                or any(relative not in block for relative in role_paths)
            ):
                findings.append(_finding("consumer", path, "Python cache"))
                break

    exact_commands = {
        Path(".github/workflows/ci.yml"): {
            "make install-bootstrap": 3,
            "make install-atlas-contract-lock": 1,
            "make install-audit-lock": 1,
            "make install-docs-lock": 1,
            "make install-torch-stack": 6,
            "make install-compiler-lock": 1,
        },
        Path(".github/workflows/docs.yml"): {
            "make install-bootstrap": 1,
            "make install-docs-lock": 1,
        },
        Path(".github/workflows/pages.yml"): {
            "make install-bootstrap": 2,
            "make install-docs-lock": 2,
        },
        Path(".github/workflows/atlas-contract.yml"): {
            "make install-bootstrap": 1,
            "make install-atlas-contract-lock": 1,
        },
    }
    for path, commands in exact_commands.items():
        source = workflow_sources[path]
        if any(source.count(command) != count for command, count in commands.items()):
            findings.append(_finding("consumer", path, "lock role"))
    ci_source = workflow_sources[Path(".github/workflows/ci.yml")]
    classifier_contract = (
        'id: dependency-scope' in ci_source
        and "--classify-event" in ci_source
        and "--github-output \"$GITHUB_OUTPUT\"" in ci_source
        and ci_source.count("steps.dependency-scope.outputs.lock-check == 'true'") == 2
        and ci_source.count("steps.dependency-scope.outputs.image-check == 'true'") == 1
        and "make verify-dependency-locks" in ci_source
        and "make audit-advisories" in ci_source
    )
    if not classifier_contract:
        findings.append(
            _finding("consumer", Path(".github/workflows/ci.yml"), "network selector")
        )

    try:
        images = {item["consumer"]: item for item in image_payload["images"]}
        docker = images["docker"]
        devcontainer = images["devcontainer"]
        docker_reference = f'{docker["source"]}@{docker["index_digest"]}'
        devcontainer_reference = (
            f'{devcontainer["source"]}@{devcontainer["index_digest"]}'
        )
    except (KeyError, TypeError):
        findings.append(_finding("consumer", image_path, "image ledger"))
    else:
        if not docker_source.startswith(f"FROM {docker_reference}\n"):
            findings.append(_finding("consumer", docker_path, "image reference"))
        if f'"image": "{devcontainer_reference}"' not in devcontainer_source:
            findings.append(
                _finding("consumer", devcontainer_path, "image reference")
            )
        docker_environment = (
            "ENV VIRTUAL_ENV=/home/jovyan/.venvs/ml-eng-lab\n" in docker_source
            and "ENV CONDA_AUTO_ACTIVATE_BASE=false\n" in docker_source
            and 'ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"\n' in docker_source
            and 'RUN /opt/conda/bin/python -m venv "$VIRTUAL_ENV" \\\n'
            in docker_source
        )
        if (
            "--platform" in docker_source
            or "make install-torch-stack" not in docker_source
            or not docker_environment
        ):
            findings.append(_finding("consumer", docker_path, "native locked build"))
    return findings


def verify_dependency_locks(repo: Path) -> tuple[LockFinding, ...]:
    try:
        policy = load_policy(repo)
    except DependencyLockError:
        return (LockFinding("policy", "requirements/lock-policy.toml", "invalid"),)
    findings: list[LockFinding] = []
    parsed: dict[Path, tuple[LockedRequirement, ...]] = {}
    for relative in policy.outputs:
        path = repo / relative
        if not path.is_file():
            findings.append(LockFinding("inventory", relative.as_posix(), "missing"))
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            findings.append(_finding("content", relative, "unreadable"))
            continue
        if any(
            token in text
            for token in (
                "/private/",
                "/Users/",
                "file:",
                "git+",
                "--extra-index-url",
                "${",
                "$(",
                "`",
            )
        ):
            findings.append(_finding("content", relative, "unsafe"))
            continue
        lines = tuple(text.splitlines())
        expected_header = _expected_header(repo, policy, _target_name(relative))
        if lines[: len(expected_header)] != expected_header:
            findings.append(_finding("header", relative, "drift"))
            continue
        try:
            requirements = parse_lock(path)
        except DependencyLockError:
            findings.append(_finding("content", relative, "invalid"))
            continue
        if not requirements:
            findings.append(_finding("content", relative, "empty"))
            continue
        parsed[relative] = requirements
    if findings:
        return tuple(findings)

    bootstrap = _requirements_by_name(parsed[Path("requirements/locks/bootstrap.txt")])
    compiler = _requirements_by_name(parsed[Path("requirements/locks/compiler.txt")])
    atlas = _requirements_by_name(parsed[Path("requirements/locks/atlas-contract.txt")])
    expected_bootstrap = {
        "pip": Version("26.1.2"),
        "setuptools": Version("81.0.0"),
        "wheel": Version("0.47.0"),
        "packaging": Version("26.2"),
    }
    if {name: item.version for name, item in bootstrap.items()} != expected_bootstrap:
        findings.append(_finding("pin", Path("requirements/locks/bootstrap.txt"), "bootstrap"))
    if {name: item.version for name, item in compiler.items()} != {"uv": Version("0.11.19")}:
        findings.append(_finding("pin", Path("requirements/locks/compiler.txt"), "compiler"))
    atlas_direct = {"pytest": Version("9.0.3"), "pyyaml": Version("6.0.3"), "uv": Version("0.11.19")}
    if any(atlas.get(name) is None or atlas[name].version != version for name, version in atlas_direct.items()):
        findings.append(_finding("pin", Path("requirements/locks/atlas-contract.txt"), "Atlas"))

    docs_requirements = parsed[Path("docs-requirements.txt")]
    for platform in policy.platforms:
        target = _target_for(platform)
        root_path = Path("requirements/locks") / platform.key / "root.txt"
        runtime_path = Path("requirements/locks") / platform.key / "runtime.txt"
        core_path = Path("requirements/locks") / platform.key / "core.txt"
        root = _requirements_by_name(parsed[root_path])
        runtime = _requirements_by_name(parsed[runtime_path])
        core = _requirements_by_name(parsed[core_path])
        docs = _requirements_by_name(docs_requirements, target)
        if not set(core) <= set(runtime) or not set(runtime) <= set(root):
            findings.append(_finding("subset", runtime_path, "core-runtime-root"))
        if not set(bootstrap) <= set(root) or not set(docs) <= set(root):
            findings.append(_finding("subset", root_path, "bootstrap-docs-root"))
        local = "" if platform.system == "Darwin" else "+cpu"
        expected_core = {
            "torch": Version(f"2.11.0{local}"),
            "torchvision": Version(f"0.26.0{local}"),
            "torchaudio": Version(f"2.11.0{local}"),
        }
        if any(
            core.get(name) is None or core[name].version != version
            for name, version in expected_core.items()
        ):
            findings.append(_finding("pin", core_path, "Torch"))
        pyg_local = "+pt211" if platform.system == "Darwin" else "+pt211cpu"
        expected_runtime = {
            "pyg-lib": Version(f"0.8.0{pyg_local}"),
            "torch-scatter": Version(
                "2.1.2" if platform.system == "Darwin" else "2.1.2+pt211cpu"
            ),
            "torch-sparse": Version(
                "0.6.18" if platform.system == "Darwin" else "0.6.18+pt211cpu"
            ),
            "torch-geometric": Version("2.8.0.post1"),
            "torchao": Version(
                "0.18.0" if platform.system == "Darwin" else "0.18.0+cpu"
            ),
        }
        if any(
            runtime.get(name) is None or runtime[name].version != version
            for name, version in expected_runtime.items()
        ):
            findings.append(_finding("pin", runtime_path, "runtime"))
        direct = [requirement for requirement in root.values() if requirement.source is not None]
        if (
            len(direct) != 1
            or direct[0].name != "en-core-web-sm"
            or direct[0].source != _MODEL_URL
            or direct[0].hashes != (_MODEL_HASH,)
        ):
            findings.append(_finding("source", root_path, "NLP model"))
        if root.get("python-louvain") is None or root["python-louvain"].version != Version("0.16"):
            findings.append(_finding("pin", root_path, "python-louvain"))
    findings.extend(_consumer_findings(repo))
    findings.extend(_documentation_findings(repo))
    return tuple(findings)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--classify-event")
    parser.add_argument("--base")
    parser.add_argument("--head")
    parser.add_argument("--github-output", type=Path)
    arguments = parser.parse_args(argv)
    repo = arguments.repo_root.resolve()
    if arguments.classify_event is not None:
        paths = None
        if arguments.classify_event in {"schedule", "workflow_dispatch"}:
            paths = ()
        elif arguments.base is not None and arguments.head is not None:
            paths = _changed_paths(repo, arguments.base, arguments.head)
        scope = classify_network_checks(arguments.classify_event, paths)
        if arguments.github_output is None:
            parser.error("--github-output is required with --classify-event")
        _write_scope(arguments.github_output, scope)
        return 0
    if any(
        value is not None
        for value in (arguments.base, arguments.head, arguments.github_output)
    ):
        parser.error("classification arguments require --classify-event")
    findings = verify_dependency_locks(repo)
    if findings:
        for finding in findings:
            print(
                f"dependency lock verification failed: {finding.category}: {finding.path}",
                file=sys.stderr,
            )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
