"""Offline validation for generated dependency lock artifacts."""

from __future__ import annotations

import argparse
import hashlib
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from packaging.version import Version

from scripts.dependency_locks import (
    DependencyLockError,
    LockedRequirement,
    TargetEnvironment,
    load_policy,
    parse_lock,
    project_for_target,
)


@dataclass(frozen=True)
class LockFinding:
    category: str
    path: str
    detail: str


_GENERATOR_LINE = "# Generated by python -m scripts.lock_dependencies; do not edit."
_MODEL_URL = (
    "https://github.com/explosion/spacy-models/releases/download/"
    "en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl"
)
_MODEL_HASH = "1932429db727d4bff3deed6b34cfc05df17794f4a52eeb26cf8928f7c1a0fb85"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _target_for(platform: object) -> TargetEnvironment:
    values = dict(platform.marker_environment)
    values.update(
        {
            "implementation_version": "3.11.0",
            "python_full_version": "3.11.0",
            "extra": "",
        }
    )
    return TargetEnvironment(key=platform.key, marker_environment=values)


def _expected_header(repo: Path, policy: object, target: str) -> tuple[str, ...]:
    lines = (
        _GENERATOR_LINE,
        f"# policy-sha256: {_sha256(repo / 'requirements/lock-policy.toml')}",
        f"# target: {target}",
    )
    inputs = tuple(
        f"# input-sha256: {relative.as_posix()}={_sha256(repo / relative)}"
        for relative in policy.inputs
    )
    return lines + inputs


def _finding(category: str, relative: Path, detail: str) -> LockFinding:
    return LockFinding(category, relative.as_posix(), detail)


def _requirements_by_name(
    requirements: Sequence[LockedRequirement], target: TargetEnvironment | None = None
) -> dict[str, LockedRequirement]:
    selected = requirements if target is None else project_for_target(requirements, target)
    return {requirement.name: requirement for requirement in selected}


def _target_name(relative: Path) -> str:
    parts = relative.parts
    if len(parts) >= 4 and parts[:2] == ("requirements", "locks"):
        return parts[2]
    return "supported-matrix"


def _consumer_findings(repo: Path) -> list[LockFinding]:
    findings: list[LockFinding] = []
    torch_path = Path("scripts/install_torch_stack.py")
    helper_path = Path("scripts/install_locked_requirements.py")
    make_path = Path("Makefile")
    try:
        torch_source = (repo / torch_path).read_text(encoding="utf-8")
        helper_source = (repo / helper_path).read_text(encoding="utf-8")
        make_source = (repo / make_path).read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return [_finding("consumer", torch_path, "missing")]
    torch_contract = (
        torch_source.count('"--require-hashes",') == 1
        and torch_source.count('"--only-binary=:all:",') == 4
        and torch_source.count('"--no-binary=python-louvain",') == 1
        and torch_source.count('"--no-build-isolation",') == 1
        and "requirements/locks/bootstrap.txt" in torch_source
        and "requirements/locks/{target}" in torch_source
        and "torch-core-requirements.txt" not in torch_source
        and '"requirements.txt"' not in torch_source
    )
    if not torch_contract:
        findings.append(_finding("consumer", torch_path, "four-stage installer"))
    role_paths = {
        '"bootstrap": "requirements/locks/bootstrap.txt"',
        '"compiler": "requirements/locks/compiler.txt"',
        '"docs": "docs-requirements.txt"',
        '"audit": "requirements/locks/audit.txt"',
        '"atlas-contract": "requirements/locks/atlas-contract.txt"',
    }
    if any(helper_source.count(fragment) != 1 for fragment in role_paths):
        findings.append(_finding("consumer", helper_path, "role map"))
    make_contract = {
        "install-bootstrap": "bootstrap",
        "install-compiler-lock": "compiler",
        "install-docs-lock": "docs",
        "install-audit-lock": "audit",
        "install-atlas-contract-lock": "atlas-contract",
    }
    for target, role in make_contract.items():
        block = f"{target}:\n\t$(PYTHON) -m scripts.install_locked_requirements {role}"
        if make_source.count(block) != 1:
            findings.append(_finding("consumer", make_path, target))
    if "spacy download" in make_source:
        findings.append(_finding("consumer", make_path, "package-changing NLP assets"))
    return findings


def verify_dependency_locks(repo: Path) -> tuple[LockFinding, ...]:
    try:
        policy = load_policy(repo)
    except DependencyLockError:
        return (LockFinding("policy", "requirements/lock-policy.toml", "invalid"),)
    findings: list[LockFinding] = []
    parsed: dict[Path, tuple[LockedRequirement, ...]] = {}
    for relative in policy.outputs:
        path = repo / relative
        if not path.is_file():
            findings.append(LockFinding("inventory", relative.as_posix(), "missing"))
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            findings.append(_finding("content", relative, "unreadable"))
            continue
        if any(
            token in text
            for token in (
                "/private/",
                "/Users/",
                "file:",
                "git+",
                "--extra-index-url",
                "${",
                "$(",
                "`",
            )
        ):
            findings.append(_finding("content", relative, "unsafe"))
            continue
        lines = tuple(text.splitlines())
        expected_header = _expected_header(repo, policy, _target_name(relative))
        if lines[: len(expected_header)] != expected_header:
            findings.append(_finding("header", relative, "drift"))
            continue
        try:
            requirements = parse_lock(path)
        except DependencyLockError:
            findings.append(_finding("content", relative, "invalid"))
            continue
        if not requirements:
            findings.append(_finding("content", relative, "empty"))
            continue
        parsed[relative] = requirements
    if findings:
        return tuple(findings)

    bootstrap = _requirements_by_name(parsed[Path("requirements/locks/bootstrap.txt")])
    compiler = _requirements_by_name(parsed[Path("requirements/locks/compiler.txt")])
    atlas = _requirements_by_name(parsed[Path("requirements/locks/atlas-contract.txt")])
    expected_bootstrap = {
        "pip": Version("26.1.2"),
        "setuptools": Version("81.0.0"),
        "wheel": Version("0.47.0"),
        "packaging": Version("26.2"),
    }
    if {name: item.version for name, item in bootstrap.items()} != expected_bootstrap:
        findings.append(_finding("pin", Path("requirements/locks/bootstrap.txt"), "bootstrap"))
    if {name: item.version for name, item in compiler.items()} != {"uv": Version("0.11.19")}:
        findings.append(_finding("pin", Path("requirements/locks/compiler.txt"), "compiler"))
    atlas_direct = {"pytest": Version("9.0.3"), "pyyaml": Version("6.0.3"), "uv": Version("0.11.19")}
    if any(atlas.get(name) is None or atlas[name].version != version for name, version in atlas_direct.items()):
        findings.append(_finding("pin", Path("requirements/locks/atlas-contract.txt"), "Atlas"))

    docs_requirements = parsed[Path("docs-requirements.txt")]
    for platform in policy.platforms:
        target = _target_for(platform)
        root_path = Path("requirements/locks") / platform.key / "root.txt"
        runtime_path = Path("requirements/locks") / platform.key / "runtime.txt"
        core_path = Path("requirements/locks") / platform.key / "core.txt"
        root = _requirements_by_name(parsed[root_path])
        runtime = _requirements_by_name(parsed[runtime_path])
        core = _requirements_by_name(parsed[core_path])
        docs = _requirements_by_name(docs_requirements, target)
        if not set(core) <= set(runtime) or not set(runtime) <= set(root):
            findings.append(_finding("subset", runtime_path, "core-runtime-root"))
        if not set(bootstrap) <= set(root) or not set(docs) <= set(root):
            findings.append(_finding("subset", root_path, "bootstrap-docs-root"))
        local = "" if platform.system == "Darwin" else "+cpu"
        expected_core = {
            "torch": Version(f"2.11.0{local}"),
            "torchvision": Version(f"0.26.0{local}"),
            "torchaudio": Version(f"2.11.0{local}"),
        }
        if any(
            core.get(name) is None or core[name].version != version
            for name, version in expected_core.items()
        ):
            findings.append(_finding("pin", core_path, "Torch"))
        pyg_local = "+pt211" if platform.system == "Darwin" else "+pt211cpu"
        expected_runtime = {
            "pyg-lib": Version(f"0.8.0{pyg_local}"),
            "torch-scatter": Version(
                "2.1.2" if platform.system == "Darwin" else "2.1.2+pt211cpu"
            ),
            "torch-sparse": Version(
                "0.6.18" if platform.system == "Darwin" else "0.6.18+pt211cpu"
            ),
            "torch-geometric": Version("2.8.0.post1"),
            "torchao": Version(
                "0.18.0" if platform.system == "Darwin" else "0.18.0+cpu"
            ),
        }
        if any(
            runtime.get(name) is None or runtime[name].version != version
            for name, version in expected_runtime.items()
        ):
            findings.append(_finding("pin", runtime_path, "runtime"))
        direct = [requirement for requirement in root.values() if requirement.source is not None]
        if (
            len(direct) != 1
            or direct[0].name != "en-core-web-sm"
            or direct[0].source != _MODEL_URL
            or direct[0].hashes != (_MODEL_HASH,)
        ):
            findings.append(_finding("source", root_path, "NLP model"))
        if root.get("python-louvain") is None or root["python-louvain"].version != Version("0.16"):
            findings.append(_finding("pin", root_path, "python-louvain"))
    findings.extend(_consumer_findings(repo))
    return tuple(findings)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    arguments = parser.parse_args(argv)
    findings = verify_dependency_locks(arguments.repo_root.resolve())
    if findings:
        for finding in findings:
            print(
                f"dependency lock verification failed: {finding.category}: {finding.path}",
                file=sys.stderr,
            )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
